parameters:
#    gs_inventario.example.class: GS\InventarioBundle\Example

services:
#    gs_inventario.example:
#        class: %gs_inventario.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
