gs_consultas_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: GSConsultasBundle:Default:index }

gs_consultas_usuario_busquedaavanzada:
    pattern: consultas/usuario/busquedaAvanzada/{numerodocumentoidentidad}.{primernombre}.{segundonombre}.{primerapellido}.{segundoapellido}.{email}.{numeroresultados}
    defaults: { _controller: GSConsultasBundle:Consultasusuario:Busquedaavanzada }
    
gs_consultas_usuario_vermas:
    pattern: consultas/usuario/verMas/{numerodocumentoidentidad}.{primernombre}.{segundonombre}.{primerapellido}.{segundoapellido}.{email}
    defaults: { _controller: GSConsultasBundle:Consultasusuario:Vermas }

gs_consultas_tema_busquedaavanzada:
    pattern: consultas/tema/busquedaAvanzada/{titulo}.{estado}.{numeroresultados}
    defaults: { _controller: GSConsultasBundle:ConsultasTema:Busquedaavanzada }
    
gs_consultas_tema_vermas:
    pattern: consultas/tema/vermas/{titulo}.{estado}
    defaults: { _controller: GSConsultasBundle:ConsultasTema:Vermas}
    
gs_consultas_recurso_busquedaavanzada:
    pattern: consultas/recurso/busquedaAvanzada/{nombre}.{tiporecurso}.{numeroresultados}
    defaults: { _controller: GSConsultasBundle:ConsultasRecurso:Busquedaavanzada }

gs_consultas_produccionintelectual_busquedaavanzadaadministrador:
    pattern: administrador/consultas/produccionintelectual/busquedaAvanzada/{titulo}.{tipoproduccion}.{primernombre}.{primerapellido}.{estado}.{numeroresultados}
    defaults: { _controller: GSConsultasBundle:ConsultasProduccionintelectual:Busquedaavanzada }
    
gs_consultas_produccionintelectual_busquedaavanzadacomunidad:
    pattern: consultas/produccionintelectual/busquedaAvanzada/{titulo}.{tipoproduccion}.{primernombre}.{primerapellido}.{numeroresultados}
    defaults: { _controller: GSConsultasBundle:ConsultasProduccionintelectual:Busquedaavanzadacomunidad }
