gs_proyectos_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: GSProyectosBundle:Default:index }

#
#ADMINISTRAR PRODUCCION TEMA
#
gs_proyectos_tema_crear:
    pattern: administrador/administrarTema/crear
    defaults: { _controller: GSProyectosBundle:Administrartema:Crear }
#Se pasa el idtema correspondiente al modelo Tema y mensaje que informa del estado de la accion
gs_proyectos_tema_modificar:
    pattern: administrador/administrarTema/modificar/{id}.{mensaje}
    defaults: { _controller: GSProyectosBundle:Administrartema:Modificar }

gs_proyectos_tema_eliminar:
    pattern: administrador/administrarTema/eliminar
    defaults: { _controller: GSProyectosBundle:Administrartema:Eliminar }

gs_proyectos_tema_buscar:
    pattern: administrador/administrarTema
    defaults: { _controller: GSProyectosBundle:Administrartema:Buscar }
#Se pasa el idtema correspondiente al modelo Tema
gs_proyectos_tema_asignarsuario:
    pattern: administrador/administrarTema/asignarUsuario/{tema}
    defaults: { _controller: GSProyectosBundle:Administrartema:Asignarusuario }
#Se pasa el numerodocumentoidentidad correspondiente al modelo Usuario
gs_proyectos_tema_eliminarusuarioasignado:
    pattern: administrador/administrarTema/eliminarUsuarioAsignado/{id}
    defaults: { _controller: GSProyectosBundle:Administrartema:Eliminarusuarioasignado }
#Se pasa el primer nombre y primer apellidos correspondiente al modelo Usuario
gs_proyectos_tema_buscarusuario:
    pattern: administrador/administrarTema/buscarUsuario/{primernombre}.{primerapellido}
    defaults: { _controller: GSProyectosBundle:Administrartema:Buscarusuario }
 
#Se pasa el idtema correspondiente al modelo Tema
gs_proyectos_tema_asignarespaciotrabajo:
    pattern: administrador/administrarTema/asignarEspacioTrabajo/{tema}
    defaults: { _controller: GSProyectosBundle:Administrartema:Asignarespaciotrabajo }
  
#Se pasa el idtema correspondiente al modelo Tema
gs_proyectos_tema_eliminarespaciotrabajo:
    pattern: administrador/administrarTema/eliminarEspacioTrabajo/{id}
    defaults: { _controller: GSProyectosBundle:Administrartema:Eliminarespaciotrabajo }
#
#ADMINISTRAR PRODUCCION INTELECTUAL
#
gs_proyectos_produccionintelectual_crear:
    pattern: administrador/administrarProduccionIntelectual/crear
    defaults: { _controller: GSProyectosBundle:Administrarproduccionintelectual:Crear }

gs_proyectos_produccionintelectual_modificar:
    pattern: administrador/administrarProduccionIntelectual/modificar
    defaults: { _controller: GSProyectosBundle:Administrarproduccionintelectual:Modificar }

gs_proyectos_produccionintelectual_eliminar:
    pattern: administrador/administrarProduccionIntelectual/eliminar
    defaults: { _controller: GSProyectosBundle:Administrarproduccionintelectual:Eliminar }

#El limite por defecto sera 30, el cual corresponde al maximo de elementos mostrados de la consulta
gs_proyectos_produccionintelectual_buscar:
    pattern: administrador/administrarProduccionIntelectual/
    defaults: { _controller: GSProyectosBundle:Administrarproduccionintelectual:Buscar }
 
#Se pasa el idtema correspondiente al modelo Tema
gs_proyectos_produccionintelectual_buscarparticipantes:
    pattern: administrador/administrarProduccionIntelectual/buscarParticipantes/{id}
    defaults: { _controller: GSProyectosBundle:Administrarproduccionintelectual:Buscarparticipantes }
    
#Se pasa el idtema correspondiente al modelo Tema 
gs_proyectos_produccionintelectual_habilitartema:
    pattern: administrador/administrarProduccionIntelectual/habilitarTema/{id}
    defaults: { _controller: GSProyectosBundle:Administrarproduccionintelectual:Habilitartema }

#
#DESARROLLAR PRODUCCION INTELECTUAL
#
gs_proyectos_desarrollarproduccionintelectual_buscar:
    pattern: usuario/produccionIntelectual/
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Buscar }
    
gs_proyectos_desarrollarproduccionintelectual_perfil:
    pattern: usuario/produccionIntelectual/perfil/
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Perfil }
    
gs_proyectos_desarrollarproduccionintelectual_catalogobibliografico:
    pattern: usuario/produccionIntelectual/catalogoBibliografico
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Catalogobibliografico }

#Se pasa el idproduccionintelectual correspondiente al modelo ProduccionIntelectual
gs_proyectos_desarrollarproduccionintelectual_catalogobibliografico_vista:
    pattern: usuario/produccionIntelectual/catalogoBibliografico/vista/{id}
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Catalogobibliograficovista }

#Se pasa el idusuario correspondiente al modelo Usuario
#Mostrar el perfil de cualquier usuario, junto a su produccion intelectual
gs_proyectos_desarrollarproduccionintelectual_perfilusuario:
    pattern: usuario/produccionIntelectual/perfilUsuario/{id}
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Perfilusuario }
    
#Se pasa el idtema correspondiente al modelo Tema
gs_proyectos_desarrollarproduccionintelectual_vista: 
    pattern: usuario/produccionIntelectual/vista/{id} 
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Vista }

    #Se pasa el idbibliografia correspondiente al modelo Bibliografia
gs_proyectos_desarrollarproduccionintelectual_elementobibliografia_vista: 
    pattern: usuario/produccionIntelectual/bibliografia/vista/{id} 
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Bibliografiavista }
    
#
#DESARROLLAR PRODUCCION INTELECTUAL - Bibliografia
#

#Se pasa el idtema correspondiente al modelo Tema
gs_proyectos_desarrollarproduccionintelectual_agregarbibliografia:
    pattern: usuario/produccionIntelectual/bibliografia/agregar/{id}
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Agregarbibliografia }
    
#Se pasa el idbibliografia correspondiente al modelo Bibliografia
gs_proyectos_desarrollarproduccionintelectual_agregarbibliografia:
    pattern: usuario/produccionIntelectual/lectuaraConProposito/agregar/{id}
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Agregarlecturaproposito }

gs_proyectos_desarrollarproduccionintelectual_eliminarbibliografia:
    pattern: usuario/produccionIntelectual/bibliografia/eliminar
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Eliminarbibliografia }

gs_proyectos_desarrollarproduccionintelectual_modificarbibliografia:
    pattern: usuario/produccionIntelectual/bibliografia/modificar
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Modificarbibliografia }

gs_proyectos_desarrollarproduccionintelectual_buscarbibliografia:
    pattern: usuario/produccionIntelectual/bibliografia/buscar
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Buscarbibliografia }

#Buscar miembros del equipo de trabajo y visualizarlos en la pagina de inicio del Desarrollo de la Producción Intelectual
#Se pasa el idtema correspondiente al modelo Tema
gs_proyectos_desarrollarproduccionintelectual_buscarmiembros:
    pattern: usuario/produccionIntelectual/buscarmiembro/{tema}.{funcion}
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Buscarmiembro }

#
#DESARROLLAR PRODUCCION INTELECTUAL - Cronograma
#

#Se pasa el idtema correspondiente al modelo Tema
gs_proyectos_desarrollarproduccionintelectual_agregaractividadcronograma:
    pattern: usuario/produccionIntelectual/cronograma/agregarActividad/{id}
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Agregaractividadcronograma }

gs_proyectos_desarrollarproduccionintelectual_eliminaractividadcronograma:
    pattern: usuario/produccionIntelectual/cronograma/eliminarActividad
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Eliminaractividadcronograma }

gs_proyectos_desarrollarproduccionintelectual_modificaractividadcronograma:
    pattern: usuario/produccionIntelectual/cronograma/modificarActividad
    defaults: { _controller: GSProyectosBundle:Desarrollarproduccionintelectual:Modificaractividadcronograma }
