gs_contenidos_index:
    pattern:  /
    defaults: { _controller: GSContenidosBundle:Index:index }
    
    
gs_contenidos_usuarios_ver:
    pattern: contenidos/usuarios/ver
    defaults: { _controller: GSContenidosBundle:Usuarios:Ver }

gs_contenidos_produccionintelectual_buscar:
    pattern: /contenidos/produccionIntelectual/{tamano}.{parametro}
    defaults: { _controller: GSContenidosBundle:Produccionintelectual:Buscar, tamano: 100, parametro: xxx}
    requirements:
        tamano:  \d+        

#Se pasa el idproduccionintelectual correspondiente al modelo Produccionintelectual
gs_contenidos_produccionintelectual_ver:
    pattern: contenidos/produccionIntelectual/ver/{id}
    defaults: { _controller: GSContenidosBundle:Produccionintelectual:Ver }
    
#Se pasa el id correspondiente al modelo User y un limite correspondiente a la 
#cantidad de resultados que pretende ver el usuario
gs_contenidos_produccionintelectual_vistaperfilusuario:
    pattern: contenidos/produccionIntelectual/perfilUsuario/vista/{id}.{limite}
    defaults: { _controller: GSContenidosBundle:Produccionintelectual:Vistaperfil, limite: 5 }
    requirements:
        limite:  \d+ 
        
gs_contenidos_produccionintelectual_temasofertados:
    pattern: contenidos/produccionIntelectual/temasOfertados
    defaults: { _controller: GSContenidosBundle:Produccionintelectual:Temasofertados }
    
gs_contenidos_produccionintelectual_ultimostemasofertados:
    pattern: contenidos/produccionIntelectual/ultimosTemasOfertados
    defaults: { _controller: GSContenidosBundle:Produccionintelectual:Ultimostemasofertados }

gs_contenidos_produccionintelectual_vertemaofertado:
    pattern: contenidos/produccionIntelectual/temasOfertados/ver/{id}
    defaults: { _controller: GSContenidosBundle:Produccionintelectual:Vertemaofertado }

gs_contenidos_errores_alertageneral:
    pattern: contenidos/errores/alertaGeneral
    defaults: { _controller: GSContenidosBundle:Errores:Alertageneral }
