parameters:
#    gs_contenidos.example.class: GS\ContenidosBundle\Example

services:
#    gs_contenidos.example:
#        class: %gs_contenidos.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
